# server default port
server:
  port: 8100

# spring boot logging level
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO

# spring jpa configuration
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/agenda
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
